# Generated by Django 4.2 on 2023-05-27 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_remove_usersdata_id_alter_usersdata_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why', models.CharField(max_length=225)),
                ('key', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('susername', models.CharField(max_length=225)),
                ('rusername', models.CharField(max_length=225)),
                ('video', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=225)),
                ('video', models.CharField(default='', max_length=500)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
